server:
  port: 9090
  context-path: /context
  display-name: cnkeep
  servlet-path: /service/*

logging:
  config: classpath:logback.xml

#swagger配置
swagger2-ui:
  enable: true
  resourcePackage: spring.boot.swagger2ui.autoconfigure.resources
  basePath: /swagger-ui



